OnlineShop.Admin/Areas/Client/Controllers/HomeClientController.cs
using System.Web.Mvc;

namespace OnlineShop.Admin.Areas.Client.Controllers
{
    public class HomeClientController : Controller
    {
        // GET: Client/HomeClient
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Content()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        public ActionResult ProductByCategory()
        {
            return View();
        }

        public ActionResult ContentByCategoryContent()
        {
            return View();
        }

        public ActionResult ContentDetail()
        {
            return View();
        }

        public ActionResult ProductDetail()
        {
            return View();
        }

        public ActionResult FindNameProduct(string productName)
        {
            ViewBag.ProductName = productName;
            return View();
        }
    }
}

OnlineShop.Admin/Areas/Client/Controllers/ShoppingCartController.cs
using OnlineShop.Admin.Models;
using OnlineShop.Business.Implementations;
using OnlineShop.Common;
using OnlineShop.Entities.Entities;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace OnlineShop.Admin.Areas.Client.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly BindDataForClientHomePageBusiness _bindDataForClientHomePageBusiness = new BindDataForClientHomePageBusiness();

        // GET: Client/ShoppingCart
        public ActionResult Index()
        {
            if (Session[OnlineShopConstants.SessionCart] == null)
            {
                Session[OnlineShopConstants.SessionCart] = new List<ShoppingCartViewModel>();
            }
            return View();
        }

        public JsonResult GetAll()
        {
            if (Session[OnlineShopConstants.SessionCart] == null)
                Session[OnlineShopConstants.SessionCart] = new List<ShoppingCartViewModel>();
            var cart = (List<ShoppingCartViewModel>)Session[OnlineShopConstants.SessionCart];
            return Json(new
            {
                data = cart,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Add(int productId)
        {
            var cart = (List<ShoppingCartViewModel>)Session[OnlineShopConstants.SessionCart];
            var product = _bindDataForClientHomePageBusiness.GetProductByIdForClientHomePage(productId);
            if (cart == null)
            {
                cart = new List<ShoppingCartViewModel>();
            }
            if (product.Data.Quantity == 0)
            {
                return Json(new
                {
                    status = false,
                    message = "Sản phẩm này hiện đang hết hàng. Vui lòng liên hệ với hotline 09.492.340.86"
                });
            }
            if (cart.Any(x => x.ProductID == productId))
            {
                foreach (var item in cart)
                {
                    if (item.ProductID == productId)
                    {
                        item.Quantity += 1;
                    }
                }
            }
            else
            {
                ShoppingCartViewModel newItem = new ShoppingCartViewModel();
                newItem.ProductID = productId;
                newItem.Product = product.Data;
                newItem.Quantity = 1;
                cart.Add(newItem);
            }

            Session[OnlineShopConstants.SessionCart] = cart;
            return Json(new
            {
                status = true
            });
        }

        [HttpPost]
        public JsonResult DeleteItem(int productId)
        {
            var cartSession = (List<ShoppingCartViewModel>)Session[OnlineShopConstants.SessionCart];
            if (cartSession != null)
            {
                cartSession.RemoveAll(x => x.ProductID == productId);
                Session[OnlineShopConstants.SessionCart] = cartSession;
                return Json(new
                {
                    status = true
                });
            }
            return Json(new
            {
                status = false
            });
        }

        [HttpPost]
        public JsonResult Update(string cartData)
        {
           var cartViewModel = new JavaScriptSerializer().Deserialize<List<ShoppingCartViewModel>>(cartData);

            var cartSession = (List<ShoppingCartViewModel>)Session[OnlineShopConstants.SessionCart];
            foreach (var item in cartSession)
            {
                foreach (var jitem in cartViewModel)
                {
                    if (item.ProductID == jitem.ProductID)
                    {
                        item.Quantity = jitem.Quantity;
                    }
                }
            }

            Session[OnlineShopConstants.SessionCart] = cartSession;
            return Json(new
            {
                status = true
            });
        }

        [HttpPost]
        public JsonResult DeleteAll()
        {
            Session[OnlineShopConstants.SessionCart] = new List<ShoppingCartViewModel>();
            return Json(new
            {
                status = true
            });
        }

        public ActionResult InsertOrders(Orders orders)
        {
            var cart = (List<ShoppingCartViewModel>)Session[OnlineShopConstants.SessionCart];
            var insertOrder = _bindDataForClientHomePageBusiness.InsertOrders(orders);
            foreach (var item in cart)
            {
                var detail = new OrderDetails();
                detail.OrderID = insertOrder.Data.OrderID;
                detail.ProductID = item.ProductID;
                detail.Quantity = item.Quantity;
                detail.Price = item.Product.Price;
                detail.Discount = item.Product.Discount;
                _bindDataForClientHomePageBusiness.InsertOrderDetails(detail);
            }
            Session[OnlineShopConstants.SessionCart] = new List<ShoppingCartViewModel>();
            return Json(new
            {
                status = true
            });
        }
    }
}

OnlineShop.Admin/Controllers/FooterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Admin.Controllers
{
    public class FooterController : Controller
    {
        // GET: Footer
        public ActionResult Index()
        {
            return View();
        }
    }
}

OnlineShop.Admin/Areas/Client/Views/Shared/_ContentLeft.cshtml
<div class="content-bottom-left">
    <div class="categories">
        <h3>Danh Mục Sản Phẩm</h3>
        <ul>
            <li ng-repeat="category in BindCategoryForClientHomePage"><a href="/Client/HomeClient/ProductByCategory?id={{category.CategoryID}}">{{category.Name}} </a></li>
        </ul>
    </div>
    <div class="buters-guide">
        <h3 style="margin-bottom: 15px;">Xem Nhiều Nhất</h3>
        <div ng-repeat="topview in BindTopViewProductForClientHomePage" style="margin-bottom: 15px; display: flex; padding-bottom: 15px; border-bottom: 1px solid #eee;">
            <div style="float:left;">
                <img ng-src="{{topview.Image}}" style="width:70px; height:70px;" alt="">
            </div>
            <p>
                <a href="/Client/HomeClient/ProductDetail?id={{topview.ProductID}}" style="color:#e44f2b; font-size: 13px; letter-spacing: -0.02em;">{{topview.Name}}</a>
                <span style="font-size: 13px;letter-spacing: -0.02em;">Lượt xem : {{topview.Views}}</span>
            </p>

        </div>
    </div>
    <div class="buters-guide">
        <h3 style="margin-bottom: 15px;">Tin Tức Mới Nhất</h3>
        <div ng-repeat="newcontent in BindNewNewsForClientHomePage" style="margin-bottom: 15px; border-bottom: 1px solid #eee;">
            <div style="float:left;">
                <img ng-src="{{newcontent.Image}}" style="width:70px; height:70px;" alt="">
            </div>
            <p><a href="/Client/HomeClient/ContentDetail?id={{newcontent.ContentID}}" style="color:#e44f2b; font-size: 13px; letter-spacing: -0.02em; text-align:justify;">{{newcontent.Title}}</a></p>
        </div>
    </div>
</div>

OnlineShop.Admin/Areas/Client/Views/Shared/_FindProductName.cshtml
<div class="search_box" ng-controller="findNameProductController">
    <span>Search</span>
    <form>
        <input type="text"
               ng-model="findproduct.ProductName">
        <input type="submit" value="" ng-click="find()">
    </form>
    <div class="clear"></div>
</div>

OnlineShop.Admin/Areas/Client/Views/Shared/_Footer.cshtml
<div class="wrap" ng-repeat="footer in BindFooterForClientHomePage">
    <div ng-bind-html="footer.Content"></div>
</div>

OnlineShop.Admin/Areas/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" ng-app="osApplication">
<head>
    <title>@(ViewBag.Title)</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>

    <link href="@Url.Content("~/Content/css/style.css")" rel="stylesheet" type="text/css" media="all">
    <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet" type="text/css" media="all">
    <link href="@Url.Content("~/Content/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" media="all">

    <link href="@Url.Content("~/Content/kendo/2017/kendo.common-material.min.css")" rel="stylesheet" type="text/css">
    <link href="@Url.Content("~/Content/kendo/2017/kendo.material.min.css")" rel="stylesheet" type="text/css">

    <script src="@Url.Content("~/Scripts/kendo/2017/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/mustache.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2017/kendo.all.min.js")"></script>

    <script src="@Url.Content("~/Content/js/jquery.openCarousel.js")"></script>
    <script src="@Url.Content("~/Content/js/easing.js")"></script>
    <script src="@Url.Content("~/Content/js/move-top.js")"></script>
    <script src="@Url.Content("~/Content/js/bootstrap.min.js")"></script>

    <script src="@Url.Content("~/Scripts/jquery.sticky.js")"></script>
    <script src="@Url.Content("~/Scripts/plugins/bootbox.min.js")"></script>
    <script src="@Url.Content("~/Scripts/plugins/section-bar.js")"></script>

    <!--popup js-->
    <script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script src="@Url.Content("~/Scripts/app/common.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")"></script>

    <!--angular-->
    <script src="@Url.Content("~/Scripts/angular.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-route.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-animate.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-resource.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-messages.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-cookies.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-kendo.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-sanitize.min.js")"></script>
    <script src="@Url.Content("~/Scripts/a/a.js")"></script>

    <!--for app-->
    <script src="@Url.Content("~/Scripts/app/constants.js")"></script>
    <script src="@Url.Content("~/Scripts/app/app.js")"></script>
    <script src="@Url.Content("~/Scripts/app/directives.js")"></script>

    <script src="@Url.Content("~/Scripts/app/clientController/clientHomePage.js")"></script>
    <script src="@Url.Content("~/Scripts/app/clientServices/clientHomePageService.js")"></script>
    <script src="@Url.Content("~/Scripts/app/clientController/findNameProductController.js")"></script>


    @RenderSection("head", false)
</head>
<body ng-controller="clientHomePage">
    <div class="header">
        <div class="wrap">
            <div class="header_top">
                <div class="logo">
                </div>
                <div class="header_top_right">
                    @Html.Partial("_FindProductName")
                </div>
                <div class="clear"></div>
            </div>
            <div class="navigation">
                <a class="toggleMenu" href="#">Menu</a>
                <ul class="nav">
                    <li>
                        <a href="@Url.Action("Index", "HomeClient")">Trang Chủ</a>
                    </li>
                    <li>
                        <a href="@Url.Action("About", "HomeClient")">Giới Thiệu</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Contact", "HomeClient")">Liên Hệ</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Content", "HomeClient")">Tin Tức</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Login", "HomeClient")">Đăng Nhập</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Register", "HomeClient")">Đăng Ký</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "ShoppingCart")">Giỏ Hàng</a>
                    </li>
                </ul>
                <span class="left-ribbon"> </span>
                <span class="right-ribbon"> </span>
            </div>
            @if (ViewBag.Message == null)
            {
                <div class="header_bottom">
                    @Html.Partial("_Slider")
                    <div class="clear"></div>
                </div>
            }
        </div>
    </div>
    <!------------End Header ------------>
    <div class="main">
        @RenderBody()
    </div>
    <div class="footer">
        @Html.Partial("_Footer")
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <a href="#" id="toTop"> </a>
    <script src="@Url.Content("~/Content/js/navigation.js")"></script>
</body>
</html>

OnlineShop.Admin/Areas/Client/Views/Shared/_LayoutNotSlider.cshtml
<!DOCTYPE html>
<html lang="en" ng-app="osApplication">
<head>
    <title>@(ViewBag.Title)</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>

    <link href="@Url.Content("~/Content/css/style.css")" rel="stylesheet" type="text/css" media="all">
    <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet" type="text/css" media="all">
    <link href="@Url.Content("~/Content/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" media="all">

    <link href="@Url.Content("~/Content/kendo/2017/kendo.common-material.min.css")" rel="stylesheet" type="text/css">
    <link href="@Url.Content("~/Content/kendo/2017/kendo.material.min.css")" rel="stylesheet" type="text/css">

    <script src="@Url.Content("~/Scripts/kendo/2017/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2017/kendo.all.min.js")"></script>

    <script src="@Url.Content("~/Content/js/jquery.openCarousel.js")"></script>
    <script src="@Url.Content("~/Content/js/easing.js")"></script>
    <script src="@Url.Content("~/Content/js/move-top.js")"></script>
    <script src="@Url.Content("~/Content/js/bootstrap.min.js")"></script>

    <script src="@Url.Content("~/Scripts/jquery.sticky.js")"></script>
    <script src="@Url.Content("~/Scripts/plugins/bootbox.min.js")"></script>
    <script src="@Url.Content("~/Scripts/plugins/section-bar.js")"></script>

    <!--popup js-->
    <script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script src="@Url.Content("~/Scripts/app/common.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")"></script>

    <!--angular-->
    <script src="@Url.Content("~/Scripts/angular.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-route.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-animate.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-resource.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-messages.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-cookies.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-kendo.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-sanitize.min.js")"></script>
    <script src="@Url.Content("~/Scripts/a/a.js")"></script>

    <!--for app-->
    <script src="@Url.Content("~/Scripts/app/constants.js")"></script>
    <script src="@Url.Content("~/Scripts/app/app.js")"></script>
    <script src="@Url.Content("~/Scripts/app/directives.js")"></script>

    <script src="@Url.Content("~/Scripts/app/clientController/clientContentByCategoryContentHomePage.js")"></script>
    <script src="@Url.Content("~/Scripts/app/clientServices/clientHomePageService.js")"></script>
    <script src="@Url.Content("~/Scripts/app/clientController/findNameProductController.js")"></script>

    @RenderSection("head", false)
</head>
<body ng-controller="clientContentByCategoryContentHomePage">
    <div class="header">
        <div class="wrap">
            <div class="header_top">
                <div class="logo">
                </div>
                <div class="header_top_right">
                    @Html.Partial("_FindProductName")
                </div>
                <div class="clear"></div>
            </div>
            <div class="navigation">
                <a class="toggleMenu" href="#">Menu</a>
                <ul class="nav">
                    <li>
                        <a href="@Url.Action("Index", "HomeClient")">Trang Chủ</a>
                    </li>
                    <li>
                        <a href="@Url.Action("About", "HomeClient")">Giới Thiệu</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Contact", "HomeClient")">Liên Hệ</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Content", "HomeClient")">Tin Tức</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Login", "HomeClient")">Đăng Nhập</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Register", "HomeClient")">Đăng Ký</a>
                    </li>
                </ul>
                <span class="left-ribbon"> </span>
                <span class="right-ribbon"> </span>
            </div>
        </div>
    </div>
    <!------------End Header ------------>
    <div class="main">
        <div class="content">
            <div class="content_bottom">
                <div class="wrap">
                    <div class="content-bottom-left">
                        <div class="categories">
                            <h3>Danh Mục Tin Tức</h3>
                            <ul>
                                <li ng-repeat="categorycontent in BindCategoryContentForClientContentPage" ng-class="categorycontent.isActive ? 'active': ''"><a href="/Client/HomeClient/ContentByCategoryContent?id={{categorycontent.CategoryContentID}}">{{categorycontent.Name}}</a></li>
                            </ul>
                        </div>
                        <div class="buters-guide">
                            <h3 style="margin-bottom: 15px;">Tin Tức Mới Nhất</h3>
                            <div ng-repeat="newcontent in BindNewNewsForClientHomePage" style="margin-bottom: 15px; border-bottom: 1px solid #eee;">
                                <div style="float:left;">
                                    <img ng-src="{{newcontent.Image}}" style="width:70px; height:70px;" alt="">
                                </div>
                                <p><a href="/Client/HomeClient/ContentDetail?id={{newcontent.ContentID}}" style="color:#e44f2b; font-size: 13px; letter-spacing: -0.02em; text-align: justify;">{{newcontent.Title}}</a></p>
                            </div>
                        </div>
                    </div>
                    @RenderBody()
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        @Html.Partial("_Footer")
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <a href="#" id="toTop"> </a>
    <script src="@Url.Content("~/Content/js/navigation.js")"></script>
</body>
</html>

OnlineShop.Admin/Areas/Client/Views/Shared/_LayoutNotSliderForProduct.cshtml
<!DOCTYPE html>
<html lang="en" ng-app="osApplication">
<head>
    <title>@(ViewBag.Title)</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>

    <link href="@Url.Content("~/Content/css/style.css")" rel="stylesheet" type="text/css" media="all">
    <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet" type="text/css" media="all">
    <link href="@Url.Content("~/Content/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" media="all">

    <link href="@Url.Content("~/Content/kendo/2017/kendo.common-material.min.css")" rel="stylesheet" type="text/css">
    <link href="@Url.Content("~/Content/kendo/2017/kendo.material.min.css")" rel="stylesheet" type="text/css">

    <script src="@Url.Content("~/Scripts/kendo/2017/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2017/kendo.all.min.js")"></script>

    <script src="@Url.Content("~/Content/js/jquery.openCarousel.js")"></script>
    <script src="@Url.Content("~/Content/js/easing.js")"></script>
    <script src="@Url.Content("~/Content/js/move-top.js")"></script>
    <script src="@Url.Content("~/Content/js/bootstrap.min.js")"></script>

    <script src="@Url.Content("~/Scripts/jquery.sticky.js")"></script>
    <script src="@Url.Content("~/Scripts/plugins/bootbox.min.js")"></script>
    <script src="@Url.Content("~/Scripts/plugins/section-bar.js")"></script>

    <!--popup js-->
    <script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script src="@Url.Content("~/Scripts/app/common.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")"></script>

    <!--angular-->
    <script src="@Url.Content("~/Scripts/angular.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-route.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-animate.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-resource.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-messages.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-cookies.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-kendo.js")"></script>
    <script src="@Url.Content("~/Scripts/angular-sanitize.min.js")"></script>
    <script src="@Url.Content("~/Scripts/a/a.js")"></script>

    <!--for app-->
    <script src="@Url.Content("~/Scripts/app/constants.js")"></script>
    <script src="@Url.Content("~/Scripts/app/app.js")"></script>
    <script src="@Url.Content("~/Scripts/app/directives.js")"></script>

    <script src="@Url.Content("~/Scripts/app/clientController/clientProductByCategoryHomePage.js")"></script>
    <script src="@Url.Content("~/Scripts/app/clientServices/clientHomePageService.js")"></script>
    <script src="@Url.Content("~/Scripts/app/clientController/findNameProductController.js")"></script>

    @RenderSection("head", false)
</head>
<body ng-controller="clientProductByCategoryHomePage">
    <div class="header">
        <div class="wrap">
            <div class="header_top">
                <div class="logo">
                </div>
                <div class="header_top_right">
                    @Html.Partial("_FindProductName")
                </div>
                <div class="clear"></div>
            </div>
            <div class="navigation">
                <a class="toggleMenu" href="#">Menu</a>
                <ul class="nav">
                    <li>
                        <a href="@Url.Action("Index", "HomeClient")">Trang Chủ</a>
                    </li>
                    <li>
                        <a href="@Url.Action("About", "HomeClient")">Giới Thiệu</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Contact", "HomeClient")">Liên Hệ</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Content", "HomeClient")">Tin Tức</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Login", "HomeClient")">Đăng Nhập</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Register", "HomeClient")">Đăng Ký</a>
                    </li>
                </ul>
                <span class="left-ribbon"> </span>
                <span class="right-ribbon"> </span>
            </div>
        </div>
    </div>
    <!------------End Header ------------>
    <div class="main">
        <div class="content">
            <div class="content_bottom">
                <div class="wrap">
                    <div class="content-bottom-left">
                        <div class="categories">
                            <h3>Danh Mục Sản Phẩm</h3>
                            <ul>
                                <li ng-repeat="category in BindCategoryForClientHomePage" ng-class="category.isActive ? 'active': ''"><a href="/Client/HomeClient/ProductByCategory?id={{category.CategoryID}}">{{category.Name}}</a></li>
                            </ul>
                        </div>
                        <div class="buters-guide">
                            <h3 style="margin-bottom: 15px;">Xem Nhiều Nhất</h3>
                            <div ng-repeat="topview in BindTopViewProductForClientHomePage" style="margin-bottom: 15px; display: flex; padding-bottom: 15px; border-bottom: 1px solid #eee;">
                                <div style="float:left;">
                                    <img ng-src="{{topview.Image}}" style="width:70px; height:70px;" alt="">
                                </div>
                                <p>
                                    <a href="/Client/HomeClient/ProductDetail?id={{topview.ProductID}}" style="color:#e44f2b; font-size: 13px; letter-spacing: -0.02em;">{{topview.Name}}</a>
                                    <span style="font-size: 13px;letter-spacing: -0.02em;">Lượt xem : {{topview.Views}}</span>
                                </p>
                            </div>
                        </div>
                    </div>
                    @RenderBody()
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        @Html.Partial("_Footer")
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $().UItoTop({ easingType: 'easeOutQuart' });

        });

        $(document).load(function () {
            var pageName = $('.content-bottom-right > h3').text().trim();
            $(".content-bottom-left .categories li." + pageName + "").addClass('active');
        });
    </script>
    <a href="#" id="toTop"> </a>
    <script src="@Url.Content("~/Content/js/navigation.js")"></script>
</body>
</html>

OnlineShop.Admin/Areas/Client/Views/Shared/_Slider.cshtml
<div class="slider-img">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" style="overflow: inherit;">
            <div class="carousel-item active">
                <img class="d-block w-100" src="~/Content/Images/SLIDE_1600x600_OFF_1.jpg" alt="First slide">
            </div>
            <div class="carousel-item" ng-repeat="slider in BindSlideForClientHomePage">
                <img class="d-block w-100" ng-src="{{slider.Image}}" alt="Second slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>